// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: api/protobuf/vo/sinohope.proto

package vo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionNotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestType   int64            `protobuf:"varint,1,opt,name=requestType,proto3" json:"requestType,omitempty"`
	RequestId     string           `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestDetail *structpb.Struct `protobuf:"bytes,3,opt,name=requestDetail,proto3" json:"requestDetail,omitempty"`
	ExtraInfo     string           `protobuf:"bytes,4,opt,name=extraInfo,proto3" json:"extraInfo,omitempty"`
}

func (x *TransactionNotifyRequest) Reset() {
	*x = TransactionNotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionNotifyRequest) ProtoMessage() {}

func (x *TransactionNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionNotifyRequest.ProtoReflect.Descriptor instead.
func (*TransactionNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_vo_sinohope_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionNotifyRequest) GetRequestType() int64 {
	if x != nil {
		return x.RequestType
	}
	return 0
}

func (x *TransactionNotifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransactionNotifyRequest) GetRequestDetail() *structpb.Struct {
	if x != nil {
		return x.RequestDetail
	}
	return nil
}

func (x *TransactionNotifyRequest) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type TransactionNotifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TransactionNotifyResponse) Reset() {
	*x = TransactionNotifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionNotifyResponse) ProtoMessage() {}

func (x *TransactionNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionNotifyResponse.ProtoReflect.Descriptor instead.
func (*TransactionNotifyResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_vo_sinohope_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionNotifyResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TransactionNotifyResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransactionNotifyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WithdrawalConfirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId     string           `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestDetail *structpb.Struct `protobuf:"bytes,3,opt,name=requestDetail,proto3" json:"requestDetail,omitempty"`
	ExtraInfo     string           `protobuf:"bytes,4,opt,name=extraInfo,proto3" json:"extraInfo,omitempty"`
}

func (x *WithdrawalConfirmRequest) Reset() {
	*x = WithdrawalConfirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawalConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalConfirmRequest) ProtoMessage() {}

func (x *WithdrawalConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalConfirmRequest.ProtoReflect.Descriptor instead.
func (*WithdrawalConfirmRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_vo_sinohope_proto_rawDescGZIP(), []int{2}
}

func (x *WithdrawalConfirmRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WithdrawalConfirmRequest) GetRequestDetail() *structpb.Struct {
	if x != nil {
		return x.RequestDetail
	}
	return nil
}

func (x *WithdrawalConfirmRequest) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type WithdrawalConfirmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	RequestId string `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Action    string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *WithdrawalConfirmResponse) Reset() {
	*x = WithdrawalConfirmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawalConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalConfirmResponse) ProtoMessage() {}

func (x *WithdrawalConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_vo_sinohope_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalConfirmResponse.ProtoReflect.Descriptor instead.
func (*WithdrawalConfirmResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_vo_sinohope_proto_rawDescGZIP(), []int{3}
}

func (x *WithdrawalConfirmResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WithdrawalConfirmResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WithdrawalConfirmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WithdrawalConfirmResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_api_protobuf_vo_sinohope_proto protoreflect.FileDescriptor

var file_api_protobuf_vo_sinohope_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76,
	0x6f, 0x2f, 0x73, 0x69, 0x6e, 0x6f, 0x68, 0x6f, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a,
	0x18, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x67, 0x0a, 0x19, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x95, 0x01, 0x0a, 0x18, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x7f, 0x0a, 0x19, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x32, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2f, 0x62, 0x32, 0x2d, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_vo_sinohope_proto_rawDescOnce sync.Once
	file_api_protobuf_vo_sinohope_proto_rawDescData = file_api_protobuf_vo_sinohope_proto_rawDesc
)

func file_api_protobuf_vo_sinohope_proto_rawDescGZIP() []byte {
	file_api_protobuf_vo_sinohope_proto_rawDescOnce.Do(func() {
		file_api_protobuf_vo_sinohope_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_vo_sinohope_proto_rawDescData)
	})
	return file_api_protobuf_vo_sinohope_proto_rawDescData
}

var file_api_protobuf_vo_sinohope_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_protobuf_vo_sinohope_proto_goTypes = []interface{}{
	(*TransactionNotifyRequest)(nil),  // 0: api.protobuf.TransactionNotifyRequest
	(*TransactionNotifyResponse)(nil), // 1: api.protobuf.TransactionNotifyResponse
	(*WithdrawalConfirmRequest)(nil),  // 2: api.protobuf.WithdrawalConfirmRequest
	(*WithdrawalConfirmResponse)(nil), // 3: api.protobuf.WithdrawalConfirmResponse
	(*structpb.Struct)(nil),           // 4: google.protobuf.Struct
}
var file_api_protobuf_vo_sinohope_proto_depIdxs = []int32{
	4, // 0: api.protobuf.TransactionNotifyRequest.requestDetail:type_name -> google.protobuf.Struct
	4, // 1: api.protobuf.WithdrawalConfirmRequest.requestDetail:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_protobuf_vo_sinohope_proto_init() }
func file_api_protobuf_vo_sinohope_proto_init() {
	if File_api_protobuf_vo_sinohope_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_vo_sinohope_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionNotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_vo_sinohope_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionNotifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_vo_sinohope_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawalConfirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_vo_sinohope_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawalConfirmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_vo_sinohope_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protobuf_vo_sinohope_proto_goTypes,
		DependencyIndexes: file_api_protobuf_vo_sinohope_proto_depIdxs,
		MessageInfos:      file_api_protobuf_vo_sinohope_proto_msgTypes,
	}.Build()
	File_api_protobuf_vo_sinohope_proto = out.File
	file_api_protobuf_vo_sinohope_proto_rawDesc = nil
	file_api_protobuf_vo_sinohope_proto_goTypes = nil
	file_api_protobuf_vo_sinohope_proto_depIdxs = nil
}
