name: Docker build latest image
on:
  push:
    branches: [dev]
  #  paths: ['src/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.PERSONAL_TOKEN }}
      - name: clone repo
        run: git clone https://${{secrets.PERSONAL_USERNAME}}:${{secrets.PERSONAL_TOKEN}}@github.com/b2network/devops.git 
      - name: modify 
        run: cd devops/devops_dev/b2-bridge/ && sed -i "s/gitTag:.*/gitTag:\ '${{github.sha}}'/g"  ${{vars.DEVOPS_PROJECT}}/dev-values*.yaml   ${{vars.DEVOPS_PROJECT}}-api/dev-values*.yaml
      - name: commit && push
        run: |
          cd devops
          git config --global  user.name ${{secrets.PERSONAL_USERNAME}}
          git config --global user.email "frankbian90@gmail.com"
          git add .
          git commit -m "update gitTag to ${{github.sha}}"
          git push origin main
